spring:
  application:
    name: spring-cloud-example-client-01

  boot:
    admin:
      client:
        url: 127.0.0.1:8077
eureka:
  client:
    service-url:
      defaultZone: http://119.23.62.173:8761/eureka/
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    shutdown:
      enabled: true

