spring:
  application:
    name: spring-cloud-example-client-01
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: "*"