turbine:
#  instanceUrlSuffix: hystrix.stream    # 指定收集路径
  appConfig: spring-cloud-example-hystrix    # 指定了需要收集监控信息的服务名，多个以“,”进行区分
  clusterNameExpression: "'default'"    # 指定集群名称,若为default则为默认集群，多个集群则通过此配置区分
  combine-host-port: true    # 此配置默认为false，则服务是以host进行区分，若设置为true则以host+port进行区分
spring:
  application:
    name: spring-cloud-example-turbine
server:
  port: 8005
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"