server:
  port: 8006
spring:
  application:
    name: spring-cloud-example-ribbon
management:
  endpoints:
    web:
      exposure:
        include: "*"
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

helloRibbonClient:
  ribbon:
    eureka:
      enabled: false
    listOfServers: 127.0.0.1:8001,127.0.0.1:8002
    ServerListRefreshInterval: 15000